### ISSUE TITLE
ign.com: breakage

### ISSUE THREAD

**Issue by JigmeDatse** [uBlockOrigin/uAssets#15636]
### Prerequisites

- [x] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/27415), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/27472) report. _These sites MUST be reported by clicking their **respective links**_.
- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [x] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [x] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [x] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [x] I have turned off all other extensions and the issue still persists. (exception "[Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers)").
- [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site or browser issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.ign.com/wikis/the-legend-of-zelda-breath-of-the-wild`

### Category

breakage

### Describe the issue

Sometimes when loading the page I get:

```
Application error: a client-side exception has occurred (see the browser console for more information).
```

other times, I will get a 504 (I think) "internal server error" which I'm not sure is related.  The console errors are:

```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cdn.ziffstatic.com/pg/ign.css:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ign.prebid.js:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
imasdk.googleapis.com/js/sdkloader/ima3.js:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
static.adsafeprotected.com/vans-adapter-google-ima.js:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
static.chartbeat.com/js/chartbeat_video.js:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
static-cdn.spot.im/production/ads/tags/v21.8.1/ads/ads.css:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
analytics-pusher.js:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.js:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
pix.spot.im/api/v1/pixels:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
g.ign.com/ign.js?cc=&url=https%3A//www.ign.com/wikis/the-legend-of-zelda-breath-of-the-wild:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cdn.static.zdbb.net/js/z0WVjCBSEeGLoxIxOQVEwQ.min.js:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
fundingchoicesmessages.google.com/f/AGSKWxUQzZVhRmj5EFdskKS5uR0bMwjVbVuXHUdduP24MmNlkGUTDYgcz13qYw_3FAJARwbw3DwkM2yoNUTrHwDJr3E=:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
fundingchoicesmessages.google.com/f/AGSKWxUQzZVhRmj5EFdskKS5uR0bMwjVbVuXHUdduP24MmNlkGUTDYgcz13qYw_3FAJARwbw3DwkM2yoNUTrHwDJr3E=:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
fundingchoicesmessages.google.com/f/AGSKWxUQzZVhRmj5EFdskKS5uR0bMwjVbVuXHUdduP24MmNlkGUTDYgcz13qYw_3FAJARwbw3DwkM2yoNUTrHwDJr3E=:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
fundingchoicesmessages.google.com/f/AGSKWxUQzZVhRmj5EFdskKS5uR0bMwjVbVuXHUdduP24MmNlkGUTDYgcz13qYw_3FAJARwbw3DwkM2yoNUTrHwDJr3E=:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
tag.wknd.ai/4317/i.js:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
pix.spot.im/api/v1/pixels:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
browser-http-intake.logs.datadoghq.com/v1/input/pub64ef987b36069aa72999d7903381703d?ddsource=browser&ddtags=sdk_version%3A3.8.0:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
mollusk.apis.ign.com/graphql?operationName=WikiPage&variables=%7B%22slug%22%3A%22the-legend-of-zelda-breath-of-the-wild%22%2C%22chapter%22%3A%22Locked_Mementos%22%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%22b1bec3e39d370ca9b0b7d0075613efbef390d258944c9a04db27131548b2ef17%22%7D%7D:1          Failed to load resource: the server responded with a status of 500 ()
mollusk.apis.ign.com/graphql:1          Failed to load resource: the server responded with a status of 500 ()
_app-23ae2d78595987aaad5e.js:1 Error: mapData.map is not a function
    at new t (_app-23ae2d78595987aaad5e.js:1:1928888)
    at _app-23ae2d78595987aaad5e.js:1:1675034
    at n (_app-23ae2d78595987aaad5e.js:1:1629730)
    at _app-23ae2d78595987aaad5e.js:1:1629655
    at new Promise (<anonymous>)
    at Object.then (_app-23ae2d78595987aaad5e.js:1:1629621)
    at Object.next (_app-23ae2d78595987aaad5e.js:1:1629740)
    at B (_app-23ae2d78595987aaad5e.js:1:1596988)
    at U (_app-23ae2d78595987aaad5e.js:1:1597494)
    at t.next (_app-23ae2d78595987aaad5e.js:1:1598027)
(anonymous) @ _app-23ae2d78595987aaad5e.js:1
_app-23ae2d78595987aaad5e.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
(anonymous) @ _app-23ae2d78595987aaad5e.js:1
main-b87df09e7fc063b37f88.js:1 Uncaught (in promise) Error: mapData.map is not a function
    at new t (_app-23ae2d78595987aaad5e.js:1:1928888)
    at _app-23ae2d78595987aaad5e.js:1:1675034
    at n (_app-23ae2d78595987aaad5e.js:1:1629730)
    at _app-23ae2d78595987aaad5e.js:1:1629655
    at new Promise (<anonymous>)
    at Object.then (_app-23ae2d78595987aaad5e.js:1:1629621)
    at Object.next (_app-23ae2d78595987aaad5e.js:1:1629740)
    at B (_app-23ae2d78595987aaad5e.js:1:1596988)
    at U (_app-23ae2d78595987aaad5e.js:1:1597494)
    at t.next (_app-23ae2d78595987aaad5e.js:1:1598027)
sentry.io/api/1215921/envelope/?sentry_key=258f7434a02a42848a43b89281bddba1&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

Similar issues *seem* to exist, though I'm not sure if they are related or not.  

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 90612
  cosmetic: 38531
  scriptlet: 16692
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64510-52, 5h.17m
    easyprivacy: 30793-1171, 1d.5h.20m
    plowe-0: 3670-868, 1d.5h.21m
    ublock-abuse: 76-0, 1d.5h.24m
    ublock-badware: 3968-109, 1h.16m
    ublock-filters: 31205-112, 1h.15m
    ublock-privacy: 258-1, 1d.5h.23m
    ublock-quick-fixes: 526-25, 21h.19m
    ublock-unbreak: 1895-42, 1h.14m
    urlhaus-1: 11473-0, 17h.18m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 473 ms (selfie)
  maxAssetCacheWait: 1293 ms
popupPanel: 
  blocked: 37
  blockedDetails: 
    ign.com: 1
    adsafeprotected.com: 1
    chartbeat.com: 1
    datadoghq.com: 1
    doubleclick.net: 1
    google.com: 5
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    scorecardresearch.com: 1
    sentry.io: 5
    spot.im: 12
    wknd.ai: 1
    zdbb.net: 1
    ziffstatic.com: 5
```
</details>

**Comment by stephenhawk8054** [comment]
Are there any other breakages on the page besides the console?

**Comment by stephenhawk8054** [comment]
I see other breakages on the above link: the video player control on Firefox does not appear.

Disabling redirection works for me:

```adb
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,3p,redirect-rule,domain=ign.com
```

Can anyone else confirm this?

**Comment by ghajini** [comment]
@stephenhawk8054 i can confirm video not play, your filter work

**Comment by gorhill** [comment]
If I delete all cookies for `ign.com`, the player does not work, we need an exception filter.

**Comment by gorhill** [comment]
Mistaken, I thought I had pulled the change in Unbreak, will revert.

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/27836
