### ISSUE TITLE
nba.sport5.co.il: breakage

### ISSUE THREAD

**Issue by eben0** [uBlockOrigin/uAssets#21674]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nba.sport5.co.il/articles.aspx?FolderID=403&docID=457077`

### Category

breakage

### Description

The video ad throws an exception when uBlock is enabled:
google is not defined

```
ReferenceError: google is not defined
    at new kf (https://watch.sport5.co.il/static/js/main.44d87468.js:2:975825)
    at new Ef (https://watch.sport5.co.il/static/js/main.44d87468.js:2:987434)
    at new If (https://watch.sport5.co.il/static/js/main.44d87468.js:2:1003988)
    at t.<anonymous> (https://watch.sport5.co.il/static/js/main.44d87468.js:2:1006487)
    at t.n [as ima] (https://watch.sport5.co.il/static/js/main.44d87468.js:2:648566)
    at Uf (https://watch.sport5.co.il/static/js/main.44d87468.js:2:1007771)
    at onInit (https://watch.sport5.co.il/static/js/main.44d87468.js:2:1022308)
    at https://watch.sport5.co.il/static/js/main.44d87468.js:2:930893
    at iu (https://watch.sport5.co.il/static/js/main.44d87468.js:2:242724)
    at Sl (https://watch.sport5.co.il/static/js/main.44d87468.js:2:262951)
```
💿 Hey developer 👋

### Other extensions used

google translate, lastpass, aliexpress search by image

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://ibb.co/K7h2kXD

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 104556
 cosmetic: 44221
 scriptlet: 19933
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76423-15, now
  easyprivacy: 33171-65, now
  plowe-0: 3784-1154, now
  ublock-badware: 7565-137, now
  ublock-filters: 36569-220, now
  ublock-privacy: 952-12, now
  ublock-quick-fixes: 145-4, now
  ublock-unbreak: 2176-32, now
  urlhaus-1: 9710-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 144 ms (selfie)
 maxAssetCacheWait: 53 ms
popupPanel:
 blocked: 30
 network:
  sport5.co.il: 1
  adobedtm.com: 2
  d2muzdhs7lpmo0.cloudfront.net: 1
  doubleclick.net: 2
  dxmdp.com: 1
  gemius.pl: 1
  googletagmanager.com: 3
  googletagservices.com: 1
  imasdk.googleapis.com: 2
  minute.ly: 1
  spot.im: 11
  taboola.com: 1
  teads.tv: 1
  tfla.xyz: 1
  tldw.me: 1
 extended:
  ###taboola-below-article-thumbnails
```
</details>

**Comment by eben0** [comment]
Thanks!
Can confirm it works.
