### ISSUE TITLE
quote.blueberrylife.com: breakage

### ISSUE THREAD

**Issue by joaocanaverde-blue** [uBlockOrigin/uAssets#25490]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://quote.blueberrylife.com/application-pre-checks`

### Category

breakage

### Description

When accessing https://quote.blueberrylife.com/application-pre-checks I get this error along with a blank page:

```
TypeError: Cannot read properties of null (reading 'textContent')
    at Object.<anonymous> (main-29a2c494445ec4d9.js:1:8794)
    at Generator.next (<anonymous>)
    at r (main-29a2c494445ec4d9.js:1:473)
    at l (main-29a2c494445ec4d9.js:1:670)
    at main-29a2c494445ec4d9.js:1:729
    at new Promise (<anonymous>)
    at Object.<anonymous> (main-29a2c494445ec4d9.js:1:611)
    at Object.V (main-29a2c494445ec4d9.js:1:9397)
    at Object.initialize (main-29a2c494445ec4d9.js:1:7409)
    at 28684 (main-29a2c494445ec4d9.js:1:16181)
    ```
    
When I open the logger, it seems to be blocking the `/application-pre-checks` page itself. Unclear why.

This happens randomly (sometimes I have to refresh multiple times in order to reproduce this). It only happens when uBlock origin is enabled.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="493" alt="Screenshot 2024-10-01 at 11 53 55" src="https://github.com/user-attachments/assets/8dce7128-5db5-4fe3-9531-f3c7d569c3be">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 149967
 cosmetic: 48432
 scriptlet: 22672
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40342-295, 11m
  ublock-badware: 11177-6, 11m
  ublock-privacy: 1299-22, 11m
  ublock-unbreak: 2480-0, 11m
  ublock-quick-fixes: 131-0, 11m
  easylist: 85631-577, 11m
  easyprivacy: 53111-642, 11m
  urlhaus-1: 25045-0, 11m
  plowe-0: 3546-0, 11m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 871 ms
 maxAssetCacheWait: 17 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by joaocanaverde-blue** [comment]
@stephenhawk8054 thanks for the reply. Can't seem to reproduce it in a new browser profile.

**Comment by stephenhawk8054** [comment]
Can you go to `chrome://extensions` page (type in URL bar) and screenshot it here?

**Comment by joaocanaverde-blue** [comment]
@stephenhawk8054 I've isolated it to 1Password in the end so feel free to close this issue. Thanks!

**Comment by stephenhawk8054** [comment]
> Other extensions used
> 
> none

Please pay attention to the prerequisites before submitting the issue. We put there for a reason.

**Comment by joaocanaverde-blue** [comment]
> > Other extensions used
> > none
> 
> Please pay attention to the prerequisites before submitting the issue. We put there for a reason.

@stephenhawk8054 Didn't notice it at the time. Apologies.
